FROM node:14-alpine3.12

WORKDIR /usr/src/client

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . ./

ENV REACT_APP_BASE_URL=http://localhost:5000/

CMD [ "yarn","start"]


